### ISSUE TITLE
TypeError: Queue() missing 1 required positional argument: 'connection'

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/crash-clouseau#31]
Seems to be regressed by #30

```
2025-05-08T23:15:14.412746+00:00 heroku[worker.1]: State changed from crashed to starting
2025-05-08T23:15:16.433813+00:00 heroku[worker.1]: Starting process with command `python -m crashclouseau.worker`
2025-05-08T23:15:17.007771+00:00 heroku[worker.1]: State changed from starting to up
2025-05-08T23:15:18.580824+00:00 app[worker.1]: Traceback (most recent call last):
2025-05-08T23:15:18.580858+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2025-05-08T23:15:18.580916+00:00 app[worker.1]: return _run_code(code, main_globals, None,
2025-05-08T23:15:18.580917+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/runpy.py", line 87, in _run_code
2025-05-08T23:15:18.580972+00:00 app[worker.1]: exec(code, run_globals)
2025-05-08T23:15:18.580973+00:00 app[worker.1]: File "/app/crashclouseau/worker.py", line 42, in <module>
2025-05-08T23:15:18.581015+00:00 app[worker.1]: worker = Worker(
2025-05-08T23:15:18.581016+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/site-packages/rq/worker.py", line 197, in __init__
2025-05-08T23:15:18.581074+00:00 app[worker.1]: for q in ensure_job_list(queues)
2025-05-08T23:15:18.581076+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/site-packages/rq/utils.py", line 196, in ensure_job_list
2025-05-08T23:15:18.581135+00:00 app[worker.1]: return list(obj) if isinstance(obj, Iterable) and not isinstance(obj, str) else [obj]
2025-05-08T23:15:18.581136+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/site-packages/rq/queue.py", line 186, in __init__
2025-05-08T23:15:18.581194+00:00 app[worker.1]: raise TypeError("Queue() missing 1 required positional argument: 'connection'")
2025-05-08T23:15:18.581204+00:00 app[worker.1]: TypeError: Queue() missing 1 required positional argument: 'connection'
2025-05-08T23:15:18.700901+00:00 heroku[worker.1]: Process exited with status 1
2025-05-08T23:15:18.725862+00:00 heroku[worker.1]: State changed from up to crashed
```
